### ISSUE TITLE
Protein changes are incorrectly calculated and/or displayed

### ISSUE THREAD

**Issue by morungos** [pughlab/cbioportal#27]
On: http://205.210.128.25:8089/case.do?cancer_study_id=wouter&sample_id=Wouters31

The protein changes are all listed as `MUTATED` rather than an actual protein change.

**Comment by morungos** [comment]
There are probably deeper issues too: in the list of mutations, the percentages are always 100% with messages like: "6 samples (100.0%) in this study have mutated BCORL1, out of which 1 (16.7%) has null mutations." Terms like "null mutations" are almost certainly bugs.

**Comment by jgsong95** [comment]
There was commented out code for reading oncotator protein changes - i uncommented and added conditions and this seemed to solve the problem with the LTS ovarian data.
However, this doesn't explain why the brca data imports normally without this added code.
