### ISSUE TITLE
Add a JSON or servlet endpoint to clear the data caches

### ISSUE THREAD

**Issue by morungos** [pughlab/cbioportal#30]
Currently, on loading a new study, we need to restart the server to pick it up as a list of studies is read on class initialization. It'd be better if we could use a warm reload mechanism to get the portal to reload key data values from an external endpoint, which could be pushed to from the loading workflows. Then a new study would be displayed without having to restart the servers.

**Comment by jgsong95** [comment]
GetCancerStudies servlet created (nothing makes calls to it at the moment)
