### ISSUE TITLE
Data Sets page is blank

### ISSUE THREAD

**Issue by tjpugh** [pughlab/cbioportal#51]
I see three data sets listed on the front page, but when I click the "Data Sets" tab, nothing is listed on http://clintracker.uhnresearch.ca:8089/data_sets.jsp

**Comment by morungos** [comment]
Yes, it does look like the data sets page is completely broken. The `cancerStudyStats` isn't available for some reason. I'm not sure we ever really tested this with our studies, but we shouldn't get this happening. 

Stacktraces:

```
Caused by: java.lang.NullPointerException
	at org.apache.jsp.data_005fsets_jsp._jspService(data_005fsets_jsp.java:136)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	... 54 more

WARNING [org.eclipse.jetty.server.HttpChannel] Could not send response error 500: javax.servlet.ServletException: org.apache.jasper.JasperException: An exception occurred processing JSP page /data_sets.jsp at line 93

90: 				 out.println("<tbody>");
91: 				 // iterate over all cancer study attributes
92: 				 int lc = 0;
93: 				 for (CancerStudyStats stats : cancerStudyStats) {
94: 					 // alternate every other row color
95: 					 out.println(((++lc % 2) == 0) ? "<tr>" : "<tr class=\"rowcolor\">");
96: 					 // cancer study name
```

**Comment by morungos** [comment]
Actually, it also seems to work in a clean build. So I'm calling this one closed.

As a secondary note: this is precisely the kind of issue that exemplifies the evils of templates and JSPs. Moving more of this into taglibs would be a big step in the right direction.
